name: Deploy

on:
  push:
    branches: [frontend]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install
        working-directory: codes/frontend/tcc-conectabook

      - name: Build
        run: npm run build
        working-directory: codes/frontend/tcc-conectabook
        env:
          VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}

      # se for fazer deploy no GitHub Pages:
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: codes/frontend/tcc-conectabook/dist